apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-aws-secrets # Name of the ExternalSecret resource
  namespace: default        # Namespace where the resulting K8s Secret will be created
spec:
  refreshInterval: "1m"     # How often to check for updates in AWS Secrets Manager
  secretStoreRef:
    name: aws-secret-store # Use the ClusterSecretStore we created
    kind: ClusterSecretStore
  target:
    name: demo-app-k8s-secrets # Name of the Kubernetes Secret to create
    creationPolicy: Owner     # Optional: Ensures the ExternalSecret owns the K8s Secret
  dataFrom:
  - extract:
      key: thrive-devops/demo-app-secrets # The name of the secret in AWS Secrets Manager
