apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store # Name for the SecretStore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # Specify your AWS region
      auth:
        jwt:
          serviceAccountRef:
            # The ServiceAccount used by External Secrets Operator
            # has the necessary IAM Role via IRSA
            name: external-secrets
            namespace: external-secrets
