apiVersion: v1
kind: Service
metadata:
  name: thrive-devops-app-service # Service name
  namespace: default # Assuming deployment in default namespace
  labels:
    app: thrive-devops-app # Consistent label
spec:
  selector:
    app: thrive-devops-app # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80 # Port the Load Balancer listens on
      targetPort: 3000 # Port the container exposes
  type: LoadBalancer # Change from ClusterIP
