apiVersion: v1
kind: Service
metadata:
  name: thrive-devops-app-service # Service name
  namespace: default # Assuming deployment in default namespace
  labels:
    app: thrive-devops-app # Consistent label
spec:
  type: ClusterIP # Internal traffic only initially
  selector:
    app: thrive-devops-app # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80 # Port the service listens on
      targetPort: 3000 # Port the container listens on (Node.js app)
